### ISSUE TITLE
ModuleNotFoundError: No module named 'urwid'

### ISSUE THREAD

**Issue by baptisteArno** [hootnot/oandapyV20-examples#26]
When launchign the `pip install -r requirements.txt` command, I have this `ModuleNotFoundError` : 
```
Collecting urwidtrees (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/88/9d/981617fa083a75cf0b5ebb0ae47c3af6fb69183be1c74cc3ac6d9a0c5964/urwidtrees-1.0.1.1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/y7/dpr7h0314j39547v43hlj2c40000gn/T/pip-install-bgli1tzw/urwidtrees/setup.py", line 4, in <module>
        import urwidtrees.version as v
      File "/private/var/folders/y7/dpr7h0314j39547v43hlj2c40000gn/T/pip-install-bgli1tzw/urwidtrees/urwidtrees/__init__.py", line 6, in <module>
        from .decoration import DecoratedTree, CollapsibleTree
      File "/private/var/folders/y7/dpr7h0314j39547v43hlj2c40000gn/T/pip-install-bgli1tzw/urwidtrees/urwidtrees/decoration.py", line 4, in <module>
        import urwid
    ModuleNotFoundError: No module named 'urwid'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/y7/dpr7h0314j39547v43hlj2c40000gn/T/pip-install-bgli1tzw/urwidtrees/
```

In order to solve this issue, I had to install `urwid` manually before installing the projects requirements : `pip install urwid`
Maybe we can find a way to solve this problem?

I'm using pip version 19.1.1 and python version 3.7.3

**Comment by hootnot** [comment]
HI,

I've experienced this myself also when I wrote this code. The `requirements.txt` file seems fine... and so I fixed it also by a manual install. It bit googling gives the impression that it is a more common issue related to `urwidtrees`.

Currently I have no plans to look further into this because it has an easy work-around
