### ISSUE TITLE
exception error in console program --V20Error

### ISSUE THREAD

**Issue by developeralgo8888** [hootnot/oandapyV20-examples#5]
developer@DEV:~/Downloads/ALGODEV/oandapyV20-examples-master# python src/oanda_console.py
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.5/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/dev/Downloads/ALGODEV/oandapyV20-examples-master/src/console/greenlets/accountdetails.py", line 24, in _run
    rv = self.api.request(r)
  File "/home/anaconda3/lib/python3.5/site-packages/oandapyV20/oandapyV20.py", line 306, in request
    request_args, headers=headers)
  File "/home/anaconda3/lib/python3.5/site-packages/oandapyV20/oandapyV20.py", line 243, in __request
    response.content.decode('utf-8'))
oandapyV20.exceptions.V20Error
Sun Jan 29 23:11:39 2017 <GAccountDetails at 0x7f1d5419a898> failed with V20Error

**Comment by hootnot** [comment]
See #3
